### ISSUE TITLE
Import file without header line

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/SuluRedirectBundle#16]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 0.1.*
| SuluRedirect Version | ---
| Browser Version | ---

#### Actual Behavior

When importing a file without header line (`source,target`) the import fails foreach line without message.

#### Expected Behavior

The import should work or fail with an accurate error message.

#### Steps to Reproduce

Upload csv file without header line.
![image](https://user-images.githubusercontent.com/1464615/31809107-70ce309e-b576-11e7-87a2-c4ab521a3cc6.png)

#### Possible Solutions

There are two possible solutions:

1. use `source,target` as default header and try to import
2. detect this issue and return an accurate error message

**Comment by niklasnatter** [comment]
Fixed in #36
