### ISSUE TITLE
Case-Insensitive unique key

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/SuluRedirectBundle#19]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 0.1.3
| SuluRedirect Version | 1.6.6
| Browser Version | none

#### Actual Behavior

Currently the unique key for `source` is case insensitive (by mysql default). This leads into that the redirect for `/test` will also work for `/Test` and the import will only allow one of them (but redirect both).

This has impact on the following code snippets:

* https://github.com/sulu/SuluRedirectBundle/pull/15/files#diff-02219834ba5c105e9f7790a812da31d0R60
* https://github.com/sulu/SuluRedirectBundle/pull/15/files#diff-02219834ba5c105e9f7790a812da31d0R119
* https://github.com/sulu/SuluRedirectBundle/blob/master/Resources/config/doctrine/RedirectRoute.orm.xml#L8

#### Expected Behavior

That should be discussed.

#### Possible Solutions

Do Nothing to keep case-insensitive unique-key or mark key as `BINARY` to make it case-sensitive.

**Comment by alexander-schranz** [comment]
@wachterjohannes As the rest of the sulu routing is case insensitive I will close this issue without any changes.
