### ISSUE TITLE
Information for uploading imports

### ISSUE THREAD

**Issue by nvdbeek** [sulu/SuluRedirectBundle#20]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

On this moment there is no information how the import is working. You can upload a csv file but you dont know what is needed for this import.

Is it possible to give feedback/information to the user how this redirect functionality is working?

Update:
Removed permissions info.

**Comment by wachterjohannes** [comment]
yes that would be quite easy and also really important

**Comment by wachterjohannes** [comment]
there is already an other issue which covers that https://github.com/sulu/SuluRedirectBundle/issues/5 if you dont think thats the same you can simply reopen this issue

**Comment by nvdbeek** [comment]
I have removed the permissions information and modified the context of this issue.

**Comment by niklasnatter** [comment]
We added an toolbar action that exports the existing routes in the desired format in in #65. The CSV generated by this export toolbar action can be used as template when creating a CSV file for an import (also described in #65) 🙂
