### ISSUE TITLE
Multi webspace support not guaranteed

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluRedirectBundle#39]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.6, 2.0.0-RC1
| SuluRedirect Version | 0.2.2, dev-devleop
| Browser Version | -

#### Actual Behavior

Currently there is no multi webspace / domain support. You can redirect to a specific domain but the source can not have a domain.

#### Expected Behavior

There should be an additional `sourceHost` property which should be set by the GoneSubscriber ({host} host will be replaced with null which is the same as matching for all domains). SourceHost can be empty so it will match all domains. If a source exist in both with and without a sourceHost it should use the redirect with the host.

**Comment by alexander-schranz** [comment]
@wachterjohannes any concerns?

**Comment by niklasnatter** [comment]
Will be fixed by https://github.com/sulu/SuluRedirectBundle/pull/53
