### ISSUE TITLE
Add translations to crowdin

### ISSUE THREAD

**Issue by kleinkoerkamp** [sulu/SuluRedirectBundle#46]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | develop
| Sulu Version | 2.0.3

#### Actual Behavior

So that it's translatable

**Comment by danrot** [comment]
Will be fixed in #47, already added the existing translations to crowdin.

**Comment by danrot** [comment]
Fixed in #47.
