### ISSUE TITLE
Implement securitycontext

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/SuluRedirectBundle#5]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | none
| SuluRedirect Version | all
| Browser Version | none

#### Actual Behavior

The security-context currently only implement the `VIEW` permission.

#### Expected Behavior

This should be extended to `ADD`, `EDIT`, `DELETE`, `UPDATE`.

**Comment by nvdbeek** [comment]
Are 'imports' getting the same permissions?

**Comment by wachterjohannes** [comment]
I think a user which is able to create a redirect should also be able to import redirects thru a file

**Comment by nvdbeek** [comment]
If the user has permission to add than the user can import redirect! :+1: 
> I think a user which is able to create a redirect should also be able to import redirects thru a file

**Comment by niklasnatter** [comment]
Fixed in #34
