### ISSUE TITLE
Tag 2.0 version

### ISSUE THREAD

**Issue by plozmun** [sulu/SuluRedirectBundle#60]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 2.0
| SuluRedirect Version | 2.x
| Browser Version | All

#### Actual Behavior

Now it's not possible to install this bundle without change stability of composer to dev. 

#### Expected Behavior

Install via composer with a stable version

#### Steps to Reproduce

composer require sulu/redirect-bundle ( with a clean install of sulu skeleton )

#### Possible Solutions

Tag a 2.0 version for Sulu. I don't know if something is missing or it's planned a release date ( if so, close this issue ) . If i can help, please tell me

**Comment by alexander-schranz** [comment]
@plozmun the missing part for the release is currently the open pull request we have to import redirects #59, to have again all features which we had in the 1.x version of the bundle.

**Comment by alexander-schranz** [comment]
You also don't need to set the stability for your all packages you can also just install a dev version using:

```
composer require sulu/redirect-bundle:"^2.0@dev" --update-with-dependencies
```

**Comment by plozmun** [comment]
Ok! Thanks @alexander-schranz !
