### ISSUE TITLE
Deleting a Page fails if "Gone on remove" is enabled

### ISSUE THREAD

**Issue by plozmun** [sulu/SuluRedirectBundle#71]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | -
| SuluRedirect Version | 2.0.0
| Browser Version | -

#### Actual Behavior

If gone on remove is enabled and you try to remove a page in admin it fails. 

GoneDocumentSubscriber try to save the page https://github.com/sulu/SuluRedirectBundle/blob/2.x/GoneSubscriber/GoneDocumentSubscriber.php#L100

but saveBydata method fails due to missing 'sourceHost' key

https://github.com/sulu/SuluRedirectBundle/blob/2.x/Manager/RedirectRouteManager.php#L41

#### Expected Behavior

The page is removed and redirect is created .

#### Possible Solutions

- Add coalescence operator in 'sourceHost' 
- Refactor method to set all arguments with typehints (BC break)

**Comment by alexander-schranz** [comment]
Thx for report, fixed in 2.0.1.
