### ISSUE TITLE
Lowercasing target URL can lead to non-working redirect

### ISSUE THREAD

**Issue by ngrie** [sulu/SuluRedirectBundle#78]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.4.0
| SuluRedirect Version | 2.0.2
| Browser Version | -

#### Actual Behavior

Since #63 the redirect bundle [lowercases all target URLs](https://github.com/sulu/SuluRedirectBundle/blob/12675b2e473360e3dee4e2e7e13dfaa3b20b9f59/Entity/RedirectRoute.php#L158), which can make the whole redirect useless depending on whether the target application's URLs are case sensitive or not.

#### Expected Behavior

The target URL is adopted as it is entered.

#### Steps to Reproduce

Add a redirect to e.g. a Spotify playlist URL (which is case sensitive). When opening the source URL, the Spotify page you get redirected to will load forever or show an error page.

#### Possible Solutions

Remove the `mb_strtolower` call for the target URL.

Would you accept this change or would this be considered a BC break?

**Comment by luca-rath** [comment]
This has been fixed in #85
