### ISSUE TITLE
Automatically add slash or validate input

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluRedirectBundle#8]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.6.0-RC1
| SuluRedirect Version | 0.1.1

#### Actual Behavior

Currently you can create a redirect rule e.g. source `test.html` which is invalid as it can never map as the slash is required `/test.html`.

#### Expected Behavior

Automatically add the `/` when saving or writing the url or validate it in the frontend.

#### Steps to Reproduce

Create rule with source `test.html`.

#### Possible Solutions

See expected behavior.

**Comment by niklasnatter** [comment]
Will be fixed by https://github.com/sulu/SuluRedirectBundle/pull/53
